---

# VHOST CUSTOM SET UP
server_name: demo.intranet
server_alias: 'www.demo.intranet'
directory_index: 'index.php'
base_path: /var/www/demo/
web_base_path: '{{ base_path }}httpdocs'
vhost_j2_file: vhost.demo.intranet.conf.j2
vhost_file: vhost.demo.intranet.conf


# MARIADB CUSTOM SETUP
databases:
    dev_demo:
        name:     'dev_demo'
        user:     'dev_demo'
        password: 'dev_demo'

    prod_demo:
        name:     'prod_demo'
        user:     'prod_demo'
        password: 'prod_demo'

mysql_server_id: 1
mysql_auto_increment_increment: 1
mysql_auto_increment_offset: 1
