#!/usr/bin/env ansible-playbook -i inventories

- name: Configure LAMP Apache2/Php56-Fpm/MariaDb Server
  hosts: demo
  sudo: True
  vars:

  vars_files:
    - group_vars/demo/apache2.yml
    - group_vars/demo/php56-fpm.yml
    - group_vars/demo/mariadb.yml
    - group_vars/demo/contents.yml
  roles:
      #  - mariadb
        - apache2
        - php56-fastcgi-fpm
      #  - xdebug
        - ntp
        - contents
  tasks:


  handlers:

    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart {{ php_fpm_service_name }}
      service: name={{php_fpm_service_name}} state=restarted